"""Registry and mission metadata owned by this simulation slice."""

from physics_playground.missions.models import MissionDefinition, MissionType
from physics_playground.models.simulations import (
    Difficulty,
    InteractiveMode,
    SimulationDefinition,
    VisualMetadata,
)

SIMULATION = SimulationDefinition(
    id="magnetic_forces",
    title="Magnetic Forces",
    icon="🧲",
    description="Cross velocity or current with a magnetic field and use the right-hand rule.",
    page_module="physics_playground.subjects.light_and_electricity.magnetic_forces.page",
    mission_group="Magnetic Forces",
    modes=tuple(InteractiveMode),
    central_question="When does a magnetic field push a charge or wire, and which way?",
    concepts=("Magnetism", "Forces", "Vectors"),
    difficulty=Difficulty.INTERMEDIATE,
    badge_count=5,
    renderer="shared-vector-direction",
    model_version="magnetic-force-1.0",
    simulation_type="Analytical + vector diagram",
    visual=VisualMetadata(
        "#7B1FA2",
        "#F3E5F5",
        "⊙⊗",
        "Velocity and magnetic-field arrows with out-of-screen force",
    ),
)

MISSIONS = (
    MissionDefinition(
        id="magnetic_predict",
        simulation_id="magnetic_forces",
        title="Predicted the parallel-field force",
        description="Predict force when motion and field are parallel.",
        hints=("The cross product contains sin θ.",),
        category=MissionType.EXPLANATION,
        difficulty=Difficulty.BEGINNER,
        prerequisites=(),
        hidden=False,
        completion_rule_id="run:magnetic_predict",
        group="Magnetic Forces",
    ),
    MissionDefinition(
        id="magnetic_zero",
        simulation_id="magnetic_forces",
        title="Made the magnetic force vanish",
        description="Align motion or current parallel to the field.",
        hints=("Use 0° or 180° between vectors.",),
        category=MissionType.DISCOVERY,
        difficulty=Difficulty.BEGINNER,
        prerequisites=("magnetic_predict",),
        hidden=False,
        completion_rule_id="run:magnetic_zero",
        group="Magnetic Forces",
    ),
    MissionDefinition(
        id="magnetic_reverse",
        simulation_id="magnetic_forces",
        title="Sent force into the screen",
        description="Create a negative signed z-force.",
        hints=("Reverse charge, current, or vector order.",),
        category=MissionType.DISCOVERY,
        difficulty=Difficulty.INTERMEDIATE,
        prerequisites=("magnetic_predict",),
        hidden=False,
        completion_rule_id="run:magnetic_reverse",
        group="Magnetic Forces",
    ),
    MissionDefinition(
        id="magnetic_wire",
        simulation_id="magnetic_forces",
        title="Pushed a current-carrying wire",
        description="Run the wire-force experiment.",
        hints=("Choose Current-carrying wire.",),
        category=MissionType.DISCOVERY,
        difficulty=Difficulty.BEGINNER,
        prerequisites=("magnetic_predict",),
        hidden=False,
        completion_rule_id="run:magnetic_wire",
        group="Magnetic Forces",
    ),
    MissionDefinition(
        id="magnetic_compare",
        simulation_id="magnetic_forces",
        title="Compared perpendicular and parallel vectors",
        description="Run the angle comparison.",
        hints=("Use Compare mode.",),
        category=MissionType.COMPARISON,
        difficulty=Difficulty.BEGINNER,
        prerequisites=("magnetic_predict",),
        hidden=False,
        completion_rule_id="run:magnetic_compare",
        group="Magnetic Forces",
    ),
)
