"""Complete simulation registry used by navigation and the home screen."""

from importlib import import_module
from types import ModuleType

from physics_playground.models.simulations import (
    Difficulty,
    InteractiveMode,
    SimulationDefinition,
    VisualMetadata,
)

LEARNING_MODES = tuple(InteractiveMode)

SIMULATION_REGISTRY = (
    SimulationDefinition(
        id="diffusion",
        title="Diffusion and Random Walks",
        icon="🟣",
        description="Follow seeded particles as random steps spread into a measurable distribution.",
        page_module="physics_playground.subjects.fluids_and_matter.diffusion.page",
        mission_group="Diffusion and Random Walks",
        modes=LEARNING_MODES,
        central_question="How can unpredictable individual steps create predictable collective spreading?",
        concepts=("Diffusion", "Probability", "Statistics"),
        difficulty=Difficulty.INTERMEDIATE,
        badge_count=5,
        renderer="shared-random-walk-player",
        model_version="diffusion-1.0",
        simulation_type="Seeded stochastic simulation",
        visual=VisualMetadata(
            "#7B1FA2", "#F3E5F5", "⋯", "Colored particle paths spreading from a common origin"
        ),
    ),
    SimulationDefinition(
        id="gas_laws",
        title="Gas Laws",
        icon="🎈",
        description="Constrain an ideal gas and compare Boyle's, Charles's, and Gay-Lussac's laws.",
        page_module="physics_playground.subjects.fluids_and_matter.gas_laws.page",
        mission_group="Gas Laws",
        modes=LEARNING_MODES,
        central_question="How do pressure, volume, temperature, and gas amount constrain one another?",
        concepts=("Gases", "Pressure", "Temperature"),
        difficulty=Difficulty.INTERMEDIATE,
        badge_count=5,
        renderer="shared-gas-piston",
        model_version="gas-laws-1.0",
        simulation_type="Analytical + piston diagram",
        visual=VisualMetadata("#F9A825", "#FFFDE7", "⇅", "Gas particles beneath a movable piston"),
    ),
    SimulationDefinition(
        id="buoyancy",
        title="Buoyancy",
        icon="🛟",
        description="Change object and fluid density to make objects float, sink, or hover.",
        page_module="physics_playground.subjects.fluids_and_matter.buoyancy.page",
        mission_group="Buoyancy",
        modes=LEARNING_MODES,
        central_question="What decides whether an object floats, sinks, or remains neutrally buoyant?",
        concepts=("Fluids", "Buoyancy", "Density"),
        difficulty=Difficulty.BEGINNER,
        badge_count=4,
        renderer="shared-fluid-container",
        model_version="buoyancy-1.0",
        simulation_type="Analytical + container diagram",
        visual=VisualMetadata("#0288D1", "#E1F5FE", "▰", "An object partly submerged in a fluid"),
    ),
    SimulationDefinition(
        id="fluid_pressure",
        title="Fluid Pressure",
        icon="🌊",
        description="Measure gauge and absolute pressure at different depths and in different fluids.",
        page_module="physics_playground.subjects.fluids_and_matter.fluid_pressure.page",
        mission_group="Fluid Pressure",
        modes=LEARNING_MODES,
        central_question="Why does pressure increase as we move deeper into a fluid?",
        concepts=("Fluids", "Pressure", "Density"),
        difficulty=Difficulty.BEGINNER,
        badge_count=4,
        renderer="shared-fluid-container",
        model_version="fluid-pressure-1.0",
        simulation_type="Analytical + column diagram",
        visual=VisualMetadata("#1565C0", "#E3F2FD", "▥", "A fluid column darkening with depth"),
    ),
    SimulationDefinition(
        id="magnetic_forces",
        title="Magnetic Forces",
        icon="🧲",
        description="Cross velocity or current with a magnetic field and use the right-hand rule.",
        page_module="physics_playground.subjects.light_and_electricity.magnetic_forces.page",
        mission_group="Magnetic Forces",
        modes=LEARNING_MODES,
        central_question="When does a magnetic field push a charge or wire, and which way?",
        concepts=("Magnetism", "Forces", "Vectors"),
        difficulty=Difficulty.INTERMEDIATE,
        badge_count=5,
        renderer="shared-vector-direction",
        model_version="magnetic-force-1.0",
        simulation_type="Analytical + vector diagram",
        visual=VisualMetadata(
            "#7B1FA2",
            "#F3E5F5",
            "⊙⊗",
            "Velocity and magnetic-field arrows with out-of-screen force",
        ),
    ),
    SimulationDefinition(
        id="electric_fields",
        title="Electric Fields",
        icon="⚡",
        description="Arrange positive and negative point charges, map vectors and potential, and probe forces.",
        page_module="physics_playground.subjects.light_and_electricity.electric_fields.page",
        mission_group="Electric Fields",
        modes=LEARNING_MODES,
        central_question="How do multiple charges shape electric field, potential, and force?",
        concepts=("Electricity", "Fields", "Potential"),
        difficulty=Difficulty.ADVANCED,
        badge_count=4,
        renderer="shared-vector-field",
        model_version="electric-field-1.0",
        simulation_type="Analytical + bounded field grid",
        visual=VisualMetadata(
            "#D32F2F", "#E3F2FD", "±", "Positive and negative charges surrounded by field arrows"
        ),
    ),
    SimulationDefinition(
        id="reflection_refraction",
        title="Reflection and Refraction",
        icon="🔦",
        description="Trace reflected and refracted rays across a boundary and discover total internal reflection.",
        page_module="physics_playground.subjects.light_and_electricity.reflection_refraction.page",
        mission_group="Reflection and Refraction",
        modes=LEARNING_MODES,
        central_question="How does light choose its direction at a boundary?",
        concepts=("Light", "Reflection", "Refraction"),
        difficulty=Difficulty.INTERMEDIATE,
        badge_count=4,
        renderer="shared-ray-diagram",
        model_version="reflection-refraction-1.0",
        simulation_type="Analytical + ray diagram",
        visual=VisualMetadata(
            "#FB8C00", "#FFF3E0", "↘", "A light ray splitting into reflected and refracted paths"
        ),
    ),
    SimulationDefinition(
        id="thin_lenses",
        title="Thin Lenses",
        icon="🔍",
        description="Build converging and diverging lens diagrams and classify their images.",
        page_module="physics_playground.subjects.light_and_electricity.thin_lenses.page",
        mission_group="Thin Lenses",
        modes=LEARNING_MODES,
        central_question="Where does a lens form an image, and is it real or virtual?",
        concepts=("Light", "Lenses", "Images"),
        difficulty=Difficulty.INTERMEDIATE,
        badge_count=4,
        renderer="shared-ray-diagram",
        model_version="thin-lens-1.0",
        simulation_type="Analytical + ray diagram",
        visual=VisualMetadata(
            "#1565C0", "#E3F2FD", ")(", "Principal rays passing through a thin lens"
        ),
    ),
    SimulationDefinition(
        id="doppler_effect",
        title="Sound and Doppler Effect",
        icon="🔊",
        description="Move a sound source and observer to hear frequency shifts and watch wavefronts bunch up.",
        page_module="physics_playground.subjects.waves_and_oscillations.doppler_effect.page",
        mission_group="Sound and Doppler Effect",
        modes=LEARNING_MODES,
        central_question="Why does a moving siren change pitch as it passes?",
        concepts=("Sound", "Doppler effect", "Waves"),
        difficulty=Difficulty.INTERMEDIATE,
        badge_count=4,
        renderer="shared-wavefront-player",
        model_version="doppler-1.0",
        simulation_type="Analytical + wavefront animation",
        visual=VisualMetadata(
            "#D32F2F", "#FFEBEE", ")))", "A moving sound source emitting expanding wavefronts"
        ),
    ),
    SimulationDefinition(
        id="wave_interference",
        title="Wave Interference",
        icon="🌊",
        description="Combine traveling waves and measure constructive and destructive interference.",
        page_module="physics_playground.subjects.waves_and_oscillations.wave_interference.page",
        mission_group="Wave Interference",
        modes=LEARNING_MODES,
        central_question="How do amplitude and phase determine the wave we observe?",
        concepts=("Waves", "Interference", "Superposition"),
        difficulty=Difficulty.INTERMEDIATE,
        badge_count=4,
        renderer="shared-scalar-field-player",
        model_version="wave-interference-1.0",
        simulation_type="Analytical + field animation",
        visual=VisualMetadata(
            "#0072B2", "#E3F2FD", "∿", "Multiple traveling waves combining into one field"
        ),
    ),
    SimulationDefinition(
        id="roller_coaster",
        title="Roller-Coaster Energy",
        icon="🎢",
        description="Trade potential and kinetic energy while testing whether a coaster can finish its track.",
        page_module="physics_playground.subjects.mechanics.roller_coaster.page",
        mission_group="Roller-Coaster Energy",
        modes=LEARNING_MODES,
        central_question="How do height and energy losses control a coaster's speed?",
        concepts=("Energy", "Conservation", "Dissipation"),
        difficulty=Difficulty.INTERMEDIATE,
        badge_count=4,
        renderer="shared-browser-player",
        model_version="roller-coaster-1.0",
        simulation_type="Analytical + sampled",
        visual=VisualMetadata("#E53935", "#FFEBEE", "🎢", "A coaster moving over hills"),
    ),
    SimulationDefinition(
        id="rotational_motion",
        title="Rotational Motion",
        icon="🌀",
        description="Apply torque to different body shapes and track angular motion and energy.",
        page_module="physics_playground.subjects.mechanics.rotational_motion.page",
        mission_group="Rotational Motion",
        modes=LEARNING_MODES,
        central_question="How does moment of inertia change rotational acceleration?",
        concepts=("Rotation", "Torque", "Energy"),
        difficulty=Difficulty.INTERMEDIATE,
        badge_count=4,
        renderer="shared-browser-player",
        model_version="rotational-motion-1.0",
        simulation_type="Analytical",
        visual=VisualMetadata("#5E35B1", "#EDE7F6", "◉", "A marked disk rotating about its center"),
    ),
    SimulationDefinition(
        id="inclined_plane",
        title="Inclined Plane",
        icon="📐",
        description="Explore how ramp angle and friction decide whether a block slides.",
        page_module="physics_playground.subjects.mechanics.inclined_plane.page",
        mission_group="Inclined Plane",
        modes=LEARNING_MODES,
        central_question="When does gravity overcome friction on a ramp?",
        concepts=("Forces", "Friction", "Acceleration"),
        difficulty=Difficulty.BEGINNER,
        badge_count=3,
        renderer="shared-browser-player",
        model_version="inclined-plane-1.0",
        simulation_type="Analytical",
        visual=VisualMetadata("#FB8C00", "#FFF3E0", "▰", "A block resting on an inclined ramp"),
    ),
    SimulationDefinition(
        id="torque_levers",
        title="Torque and Levers",
        icon="⚖️",
        description="Balance forces around a pivot and build mechanical advantage.",
        page_module="physics_playground.subjects.mechanics.torque_levers.page",
        mission_group="Torque and Levers",
        modes=LEARNING_MODES,
        central_question="How do force and distance combine to turn a lever?",
        concepts=("Torque", "Levers", "Equilibrium"),
        difficulty=Difficulty.BEGINNER,
        badge_count=3,
        renderer="shared-browser-player",
        model_version="lever-1.0",
        simulation_type="Analytical",
        visual=VisualMetadata("#1565C0", "#E3F2FD", "↔", "A beam balancing on a central pivot"),
    ),
    SimulationDefinition(
        id="center_of_mass",
        title="Center of Mass",
        icon="🎯",
        description="Arrange masses and find the point where the system balances.",
        page_module="physics_playground.subjects.mechanics.center_of_mass.page",
        mission_group="Center of Mass",
        modes=LEARNING_MODES,
        central_question="Where is the balance point of several objects?",
        concepts=("Center of mass", "Balance", "Weighted averages"),
        difficulty=Difficulty.BEGINNER,
        badge_count=3,
        renderer="shared-browser-player",
        model_version="center-of-mass-1.0",
        simulation_type="Analytical",
        visual=VisualMetadata(
            "#00897B", "#E0F2F1", "●", "Several masses arranged along a balance line"
        ),
    ),
    SimulationDefinition(
        id="earth_tunnel",
        title="The Big Fall",
        icon="🕳️",
        description="Fall through a tunnel across an idealized planet.",
        page_module="physics_playground.subjects.mechanics.earth_tunnel.page",
        mission_group="The Big Fall",
        modes=LEARNING_MODES,
        central_question="How long would it take to fall through an entire planet?",
        concepts=("Gravity", "Simple harmonic motion", "Energy"),
        difficulty=Difficulty.INTERMEDIATE,
        badge_count=3,
        renderer="shared-browser-player",
        model_version="tunnel-2.0",
        simulation_type="Analytical + numerical",
        visual=VisualMetadata("#7E57C2", "#EDE7F6", "🌍", "A traveler falling through a planet"),
    ),
    SimulationDefinition(
        id="orbital_gravity",
        title="Planet Launcher",
        icon="🪐",
        description="Launch a planet and discover crashes, orbits, and escape.",
        page_module="physics_playground.subjects.mechanics.orbital_gravity.page",
        mission_group="Planet Launcher",
        modes=LEARNING_MODES,
        central_question="How fast must a planet move to stay in orbit?",
        concepts=("Gravity", "Orbits", "Conservation"),
        difficulty=Difficulty.ADVANCED,
        badge_count=4,
        renderer="shared-browser-player",
        model_version="orbit-verlet-1.0",
        simulation_type="Numerical",
        visual=VisualMetadata("#3949AB", "#E8EAF6", "☀️", "A planet orbiting a central star"),
    ),
    SimulationDefinition(
        id="pendulum",
        title="The Swing Machine",
        icon="🎢",
        description="Explore how length, gravity, and angle change a swing.",
        page_module="physics_playground.subjects.waves_and_oscillations.pendulum.page",
        mission_group="The Swing Machine",
        modes=LEARNING_MODES,
        central_question="What controls how long a swing takes?",
        concepts=("Oscillation", "Gravity", "Approximation"),
        difficulty=Difficulty.BEGINNER,
        badge_count=3,
        renderer="shared-browser-player",
        model_version="pendulum-2.0",
        simulation_type="Analytical + numerical",
        visual=VisualMetadata("#43A047", "#E8F5E9", "●", "A pendulum swinging from a support"),
    ),
    SimulationDefinition(
        id="cannonball",
        title="Cannonball Launcher",
        icon="🎯",
        description="Aim a projectile and compare ideal and drag-filled flight.",
        page_module="physics_playground.subjects.mechanics.cannonball.page",
        mission_group="Cannonball Launcher",
        modes=LEARNING_MODES,
        central_question="Which launch angle sends a cannonball farthest?",
        concepts=("Projectile motion", "Energy", "Air resistance"),
        difficulty=Difficulty.INTERMEDIATE,
        badge_count=4,
        renderer="shared-browser-player",
        model_version="projectile-2.0",
        simulation_type="Analytical + numerical",
        visual=VisualMetadata("#E53935", "#FFEBEE", "💥", "A cannonball arcing toward a target"),
    ),
    SimulationDefinition(
        id="boing",
        title="The Boing Machine",
        icon="🌀",
        description="Build an oscillator and hunt for resonance.",
        page_module="physics_playground.subjects.waves_and_oscillations.boing.page",
        mission_group="Boing Machine",
        modes=LEARNING_MODES,
        central_question="What controls a spring's rhythm—and when does resonance appear?",
        concepts=("Oscillation", "Resonance", "Energy"),
        difficulty=Difficulty.INTERMEDIATE,
        badge_count=4,
        renderer="shared-browser-player",
        model_version="spring-2.0",
        simulation_type="Analytical + numerical",
        visual=VisualMetadata("#5C6BC0", "#E8EAF6", "↔️", "A mass oscillating on a spring"),
    ),
    SimulationDefinition(
        id="double_pendulum",
        title="Double Pendulum of Chaos",
        icon="🌀",
        description="Watch a tiny difference grow into completely different motion.",
        page_module="physics_playground.subjects.waves_and_oscillations.double_pendulum.page",
        mission_group="Double Pendulum of Chaos",
        modes=LEARNING_MODES,
        central_question="How can nearly identical starts produce different futures?",
        concepts=("Chaos", "Nonlinear dynamics", "Energy"),
        difficulty=Difficulty.ADVANCED,
        badge_count=3,
        renderer="shared-browser-player",
        model_version="double-pendulum-rk4-2.0",
        simulation_type="Numerical",
        visual=VisualMetadata("#8E24AA", "#F3E5F5", "〽️", "Two nearly identical double pendulums"),
    ),
    SimulationDefinition(
        id="bumper_cars",
        title="Bumper Cars",
        icon="🚗",
        description="Crash two cars and track momentum and energy.",
        page_module="physics_playground.subjects.mechanics.bumper_cars.page",
        mission_group="Bumper Cars",
        modes=LEARNING_MODES,
        central_question="What determines how two cars move after a collision?",
        concepts=("Momentum", "Energy", "Collisions"),
        difficulty=Difficulty.BEGINNER,
        badge_count=4,
        renderer="shared-browser-player",
        model_version="collision-1.0",
        simulation_type="Analytical",
        visual=VisualMetadata(
            "#FB8C00", "#FFF3E0", "🚙", "Two bumper cars approaching a collision"
        ),
    ),
)
SIMULATIONS_BY_ID = {definition.id: definition for definition in SIMULATION_REGISTRY}


def load_validated_page(simulation_id: str) -> tuple[ModuleType, str]:
    """Resolve a simulation page only after validating its manifest."""

    catalog = import_module("physics_playground.expansion_catalog")
    validation = import_module("physics_playground.expansion_validation")
    manifest = catalog.EXPANSION_BY_ID[simulation_id]
    validation.validate_expansion_definition(manifest)
    module_name, function_name = manifest.page_entrypoint.rsplit(".", 1)
    return import_module(module_name), function_name
