"""Reusable responsive shared-player renderer for geometric ray diagrams."""
from physics_playground.canvas.player import build_player_document
SCENE=r"""
const scene={draw(ctx,s){const w=s.transform.width,h=s.transform.height,c=s.config.rayConfig||{},rays=c.rays||[],xmin=c.xmin??-5,xmax=c.xmax??5,ymin=c.ymin??-4,ymax=c.ymax??4,X=x=>35+(x-xmin)/(xmax-xmin)*(w-70),Y=y=>h-30-(y-ymin)/(ymax-ymin)*(h-60);PhysicsExperience.context(ctx,s,'opticsBench');
if(c.interface)PhysicsAnnotations.normalLine(ctx,s,{x:X(0),y:Y(0),length:w-70,surface_angle:Math.PI/2,label:'Normal'});ctx.strokeStyle=PhysicsVisuals.token(s,'colors','text_muted','#526577');ctx.beginPath();ctx.moveTo(X(xmin),Y(0));ctx.lineTo(X(xmax),Y(0));ctx.stroke();
if(c.interface)PhysicsAssets.mirror(ctx,s,{x:X(0),y:Y(0),height:h-60,shadow:false,label:'Interface'});if(c.lens)PhysicsAssets.lens(ctx,s,{x:X(0),y:Y(0),width:Math.max(18,w*.035),height:(h-60)*.75,fill:PhysicsVisuals.token(s,'colors','electric_field','#006D77'),shadow:true,label:c.lensSign>0?'Converging lens':'Diverging lens'});
const visible=Math.ceil(s.fraction*rays.length);for(let i=0;i<visible;i++){const r=rays[i],virtual=r.kind==='virtual',color=PhysicsVisuals.token(s,'colors',virtual?'magnetic_field':(i===0?'net_force':'energy'),'#B45309');PhysicsAssets.ray(ctx,s,{x:X(r.x1),y:Y(r.y1),end:{x:X(r.x2),y:Y(r.y2)},fill:color,lineWidth:2.5,dashed:virtual,label:PhysicsVisuals.responsive(s)==='mobile'?'':(r.label||''),shadow:false})}}};
"""
def build_ray_diagram(*,rays:list[dict],message:str,seed:int,interface:bool=False,lens:bool=False,lens_sign:int=1,bounds:tuple[float,float,float,float]=(-5,5,-4,4))->str:
    xmin,xmax,ymin,ymax=bounds;config={"durationMs":1800,"autoplay":False,"seed":seed,"tracks":[{"id":"ray-progress","label":"Ray construction","x":[0,1]}],"events":[],"completionMessage":message,"rayConfig":{"rays":rays,"interface":interface,"lens":lens,"lensSign":lens_sign,"xmin":xmin,"xmax":xmax,"ymin":ymin,"ymax":ymax},"view":{"minimum":0,"maximum":1}}
    return build_player_document(config=config,scene_javascript=SCENE,logical_width=820,logical_height=430,accessible_label="Geometric ray diagram. "+message,idle_hint="Press Play to construct the rays")
