from physics_playground.expansion_validation import validate_expansion_definition
from physics_playground.missions.definitions import MISSIONS_BY_SIMULATION
from physics_playground.subjects.light_and_electricity.manifests import ELECTRIC_FIELD_MANIFEST
def test_electric_field_manifest_passes():validate_expansion_definition(ELECTRIC_FIELD_MANIFEST)
def test_electric_field_has_four_missions():assert len(MISSIONS_BY_SIMULATION["electric_fields"])==4
