"""Registry and mission metadata owned by this simulation slice."""

from physics_playground.missions.models import MissionDefinition, MissionType
from physics_playground.models.simulations import (
    Difficulty,
    LearningMode,
    SimulationDefinition,
    VisualMetadata,
)
from physics_playground.subjects.fluids_and_matter.gas_laws.physics import GAS_LAWS_MODEL_VERSION

SIMULATION = SimulationDefinition(
    id="gas_laws",
    title="Gas Laws",
    icon="🎈",
    description="Constrain an ideal gas and compare Boyle's, Charles's, and Gay-Lussac's laws.",
    page_module="physics_playground.subjects.fluids_and_matter.gas_laws.page",
    mission_group="Gas Laws",
    modes=tuple(LearningMode),
    central_question="How do pressure, volume, temperature, and gas amount constrain one another?",
    concepts=("Gases", "Pressure", "Temperature"),
    difficulty=Difficulty.INTERMEDIATE,
    badge_count=5,
    renderer="shared-gas-piston",
    model_version=GAS_LAWS_MODEL_VERSION,
    simulation_type="Analytical + piston diagram",
    visual=VisualMetadata(
        "#F9A825",
        "#FFFDE7",
        "⇅",
        "Gas particles beneath a movable piston",
    ),
)

MISSIONS = (
    MissionDefinition(
        id="gas_predict",
        simulation_id="gas_laws",
        title="Predicted Boyle's compression",
        description="Predict pressure when isothermal volume is halved.",
        hints=("PV stays constant.",),
        category=MissionType.EXPLANATION,
        difficulty=Difficulty.BEGINNER,
        prerequisites=(),
        hidden=False,
        completion_rule_id="run:gas_predict",
        group="Gas Laws",
    ),
    MissionDefinition(
        id="gas_boyle",
        simulation_id="gas_laws",
        title="Ran Boyle's law",
        description="Complete an isothermal pressure–volume process.",
        hints=("Choose Boyle's law.",),
        category=MissionType.DISCOVERY,
        difficulty=Difficulty.BEGINNER,
        prerequisites=("gas_predict",),
        hidden=False,
        completion_rule_id="run:gas_boyle",
        group="Gas Laws",
    ),
    MissionDefinition(
        id="gas_charles",
        simulation_id="gas_laws",
        title="Ran Charles's law",
        description="Complete a constant-pressure volume–temperature process.",
        hints=("Choose Charles's law.",),
        category=MissionType.DISCOVERY,
        difficulty=Difficulty.BEGINNER,
        prerequisites=("gas_predict",),
        hidden=False,
        completion_rule_id="run:gas_charles",
        group="Gas Laws",
    ),
    MissionDefinition(
        id="gas_gay_lussac",
        simulation_id="gas_laws",
        title="Ran Gay-Lussac's law",
        description="Complete a constant-volume pressure–temperature process.",
        hints=("Choose Gay-Lussac's law.",),
        category=MissionType.DISCOVERY,
        difficulty=Difficulty.BEGINNER,
        prerequisites=("gas_predict",),
        hidden=False,
        completion_rule_id="run:gas_gay_lussac",
        group="Gas Laws",
    ),
    MissionDefinition(
        id="gas_compare",
        simulation_id="gas_laws",
        title="Compared constrained gas processes",
        description="Compare compression with heating.",
        hints=("Use Compare mode.",),
        category=MissionType.COMPARISON,
        difficulty=Difficulty.BEGINNER,
        prerequisites=("gas_predict",),
        hidden=False,
        completion_rule_id="run:gas_compare",
        group="Gas Laws",
    ),
)
