"""Registry and mission metadata owned by this simulation slice."""

from physics_playground.missions.models import MissionDefinition, MissionType
from physics_playground.models.simulations import (
    Difficulty,
    InteractiveMode,
    SimulationDefinition,
    VisualMetadata,
)

SIMULATION = SimulationDefinition(
    id="diffusion",
    title="Diffusion and Random Walks",
    icon="🟣",
    description="Follow seeded particles as random steps spread into a measurable distribution.",
    page_module="physics_playground.subjects.fluids_and_matter.diffusion.page",
    mission_group="Diffusion and Random Walks",
    modes=tuple(InteractiveMode),
    central_question="How can unpredictable individual steps create predictable collective spreading?",
    concepts=("Diffusion", "Probability", "Statistics"),
    difficulty=Difficulty.INTERMEDIATE,
    badge_count=5,
    renderer="shared-random-walk-player",
    model_version="diffusion-1.0",
    simulation_type="Seeded stochastic simulation",
    visual=VisualMetadata(
        "#7B1FA2",
        "#F3E5F5",
        "⋯",
        "Colored particle paths spreading from a common origin",
    ),
)

MISSIONS = (
    MissionDefinition(
        id="diffusion_predict",
        simulation_id="diffusion",
        title="Predicted diffusive spreading",
        description="Predict how mean-squared displacement changes with time.",
        hints=("Squared distances do not cancel.",),
        category=MissionType.EXPLANATION,
        difficulty=Difficulty.BEGINNER,
        prerequisites=(),
        hidden=False,
        completion_rule_id="run:diffusion_predict",
        group="Diffusion and Random Walks",
    ),
    MissionDefinition(
        id="diffusion_unbiased",
        simulation_id="diffusion",
        title="Released unbiased walkers",
        description="Run a walk with zero directional bias.",
        hints=("Set both bias controls to zero.",),
        category=MissionType.DISCOVERY,
        difficulty=Difficulty.BEGINNER,
        prerequisites=("diffusion_predict",),
        hidden=False,
        completion_rule_id="run:diffusion_unbiased",
        group="Diffusion and Random Walks",
    ),
    MissionDefinition(
        id="diffusion_two_d",
        simulation_id="diffusion",
        title="Explored two dimensions",
        description="Run particles that can move horizontally and vertically.",
        hints=("Choose 2D.",),
        category=MissionType.DISCOVERY,
        difficulty=Difficulty.BEGINNER,
        prerequisites=("diffusion_predict",),
        hidden=False,
        completion_rule_id="run:diffusion_two_d",
        group="Diffusion and Random Walks",
    ),
    MissionDefinition(
        id="diffusion_bias",
        simulation_id="diffusion",
        title="Created directed drift",
        description="Run with a noticeable directional bias.",
        hints=("Move a bias control beyond 0.10.",),
        category=MissionType.DISCOVERY,
        difficulty=Difficulty.BEGINNER,
        prerequisites=("diffusion_predict",),
        hidden=False,
        completion_rule_id="run:diffusion_bias",
        group="Diffusion and Random Walks",
    ),
    MissionDefinition(
        id="diffusion_compare",
        simulation_id="diffusion",
        title="Compared drift and diffusion",
        description="Run the unbiased-versus-biased comparison.",
        hints=("Use Compare mode.",),
        category=MissionType.COMPARISON,
        difficulty=Difficulty.BEGINNER,
        prerequisites=("diffusion_predict",),
        hidden=False,
        completion_rule_id="run:diffusion_compare",
        group="Diffusion and Random Walks",
    ),
)
