"""Structured mission catalog preserving existing and expansion achievements."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from physics_playground.models.simulations import Difficulty


class MissionType(StrEnum):
    DISCOVERY = "Discovery"
    COMPARISON = "Comparison"
    EXPLANATION = "Explanation"


@dataclass(frozen=True, slots=True)
class MissionDefinition:
    id: str
    simulation_id: str
    title: str
    description: str
    hints: tuple[str, ...]
    category: MissionType
    difficulty: Difficulty
    prerequisites: tuple[str, ...]
    hidden: bool
    completion_rule_id: str
    group: str

    @property
    def label(self):
        return self.title

    @property
    def hint(self):
        return self.hints[0] if self.hints else ""


def m(
    id,
    sim,
    title,
    description,
    hints,
    category=MissionType.DISCOVERY,
    difficulty=Difficulty.BEGINNER,
    prerequisites=(),
    hidden=False,
    group="",
):
    return MissionDefinition(
        id,
        sim,
        title,
        description,
        tuple(hints),
        category,
        difficulty,
        tuple(prerequisites),
        hidden,
        f"run:{id}",
        group,
    )


MISSION_DEFINITIONS = {
    item.id: item
    for item in (
        m(
            "tunnel_predict",
            "earth_tunnel",
            "Guessed how long the Big Fall takes",
            "Predict the ideal Earth-tunnel travel time.",
            ("Think in minutes, not hours.", "The motion behaves like a planet-sized oscillator."),
            MissionType.EXPLANATION,
            group="The Big Fall",
        ),
        m(
            "tunnel_halfway",
            "earth_tunnel",
            "Solved the Halfway Mystery",
            "Run a fall beginning halfway down.",
            ("Change the starting point.", "Distance changes, but so does maximum speed."),
            MissionType.COMPARISON,
            prerequisites=("tunnel_predict",),
            group="The Big Fall",
        ),
        m(
            "tunnel_speedy",
            "earth_tunnel",
            "Made the fall take under 20 minutes",
            "Design a fast custom planet.",
            ("Use a custom planet.", "Try a smaller radius and stronger gravity."),
            difficulty=Difficulty.INTERMEDIATE,
            prerequisites=("tunnel_predict",),
            group="The Big Fall",
        ),
        m(
            "pend_predict",
            "pendulum",
            "Guessed the swing secret",
            "Predict the small-angle period behavior.",
            ("Think about pendulum clocks.",),
            MissionType.EXPLANATION,
            group="The Swing Machine",
        ),
        m(
            "pend_four",
            "pendulum",
            "Built a perfect 4-second swing",
            "Create a period between 3.9 and 4.1 seconds.",
            ("Period grows with rope length.", "Try changing length or gravity."),
            MissionType.DISCOVERY,
            Difficulty.INTERMEDIATE,
            ("pend_predict",),
            group="The Swing Machine",
        ),
        m(
            "pend_moon",
            "pendulum",
            "Went swinging on the Moon",
            "Run a pendulum using lunar gravity.",
            ("Change the world to the Moon.",),
            prerequisites=("pend_predict",),
            group="The Swing Machine",
        ),
        m(
            "orbit_predict",
            "orbital_gravity",
            "Guessed what a slow throw does",
            "Predict a low-speed planetary launch.",
            ("Sideways motion fights an inward fall.",),
            MissionType.EXPLANATION,
            Difficulty.INTERMEDIATE,
            group="Planet Launcher",
        ),
        m(
            "orbit_crash",
            "orbital_gravity",
            "Crashed a planet into the Sun",
            "Produce a crash outcome.",
            ("Use less sideways speed.", "Try well below circular speed."),
            prerequisites=("orbit_predict",),
            group="Planet Launcher",
        ),
        m(
            "orbit_escape",
            "orbital_gravity",
            "Launched a planet into deep space",
            "Produce an escape outcome.",
            ("Compare launch speed with the escape marker.",),
            difficulty=Difficulty.INTERMEDIATE,
            prerequisites=("orbit_predict",),
            group="Planet Launcher",
        ),
        m(
            "orbit_egg",
            "orbital_gravity",
            "Made an egg-shaped orbit",
            "Create a clearly elliptical bound orbit.",
            ("Stay below escape speed but away from circular speed.",),
            MissionType.COMPARISON,
            Difficulty.ADVANCED,
            ("orbit_predict",),
            hidden=True,
            group="Planet Launcher",
        ),
        m(
            "cannon_predict",
            "cannonball",
            "Guessed the best launch angle",
            "Predict the ideal maximum-range angle.",
            ("Balance upward and horizontal motion.",),
            MissionType.EXPLANATION,
            group="Cannonball Launcher",
        ),
        m(
            "cannon_sweet_spot",
            "cannonball",
            "Fired at the 45° sweet spot",
            "Run a launch between 43° and 47°.",
            ("The ideal range formula contains sin(2θ).",),
            prerequisites=("cannon_predict",),
            group="Cannonball Launcher",
        ),
        m(
            "cannon_bullseye",
            "cannonball",
            "Hit the target",
            "Land within two meters of the target.",
            (
                "Reuse the target while adjusting speed.",
                "Use range feedback to bracket the target.",
            ),
            difficulty=Difficulty.INTERMEDIATE,
            prerequisites=("cannon_predict",),
            group="Cannonball Launcher",
        ),
        m(
            "cannon_moon",
            "cannonball",
            "Fired a cannon on the Moon",
            "Complete a lunar launch.",
            ("Change the world to the Moon.",),
            prerequisites=("cannon_predict",),
            group="Cannonball Launcher",
        ),
        m(
            "spring_predict",
            "boing",
            "Guessed the boing secret",
            "Predict whether ideal amplitude changes period.",
            ("Ideal SHM has a hidden timing symmetry.",),
            MissionType.EXPLANATION,
            group="Boing Machine",
        ),
        m(
            "spring_two_second",
            "boing",
            "Built a perfect 2-second boing",
            "Create a period between 1.9 and 2.1 seconds.",
            ("Increase mass to slow it down.", "Increase stiffness to speed it up."),
            difficulty=Difficulty.INTERMEDIATE,
            prerequisites=("spring_predict",),
            group="Boing Machine",
        ),
        m(
            "spring_fast",
            "boing",
            "Made a boing take under half a second",
            "Create a period below 0.5 seconds.",
            ("Use a light mass and stiff spring.",),
            difficulty=Difficulty.INTERMEDIATE,
            prerequisites=("spring_predict",),
            group="Boing Machine",
        ),
        m(
            "spring_resonance",
            "boing",
            "Found resonance in Model mode",
            "Create a large response near natural-frequency driving.",
            ("Turn on driving.", "Choose the natural-frequency preset and keep damping modest."),
            MissionType.COMPARISON,
            Difficulty.ADVANCED,
            ("spring_predict",),
            hidden=True,
            group="Boing Machine",
        ),
        m(
            "chaos_predict",
            "double_pendulum",
            "Guessed what happens to nearly-identical swings",
            "Predict sensitive dependence on initial conditions.",
            ("Tiny differences can grow in nonlinear systems.",),
            MissionType.EXPLANATION,
            Difficulty.INTERMEDIATE,
            group="Double Pendulum of Chaos",
        ),
        m(
            "chaos_diverge",
            "double_pendulum",
            "Watched two close swings split apart",
            "Produce more than 0.5 m final separation.",
            (
                "Give the systems a tiny nonzero perturbation.",
                "Try energetic starting angles and more time.",
            ),
            difficulty=Difficulty.INTERMEDIATE,
            prerequisites=("chaos_predict",),
            group="Double Pendulum of Chaos",
        ),
        m(
            "chaos_flip",
            "double_pendulum",
            "Made the second arm flip all the way around",
            "Drive arm two beyond π radians.",
            ("Use a high-energy initial configuration.",),
            difficulty=Difficulty.ADVANCED,
            prerequisites=("chaos_predict",),
            hidden=True,
            group="Double Pendulum of Chaos",
        ),
        m(
            "collision_predict",
            "bumper_cars",
            "Guessed what happens in an equal-mass crash",
            "Predict an elastic equal-mass collision.",
            ("Think of Newton's cradle.",),
            MissionType.EXPLANATION,
            group="Bumper Cars",
        ),
        m(
            "collision_swap",
            "bumper_cars",
            "Made two equal cars swap velocities",
            "Run an elastic collision with nearly equal masses.",
            ("Use equal masses and bouncy bumpers.", "Start Car B nearly still."),
            MissionType.COMPARISON,
            Difficulty.INTERMEDIATE,
            ("collision_predict",),
            group="Bumper Cars",
        ),
        m(
            "collision_stop",
            "bumper_cars",
            "Stuck two cars together for a perfect stop",
            "Balance momentum with sticky bumpers.",
            ("Choose sticky bumpers.", "Make the incoming momenta cancel."),
            difficulty=Difficulty.INTERMEDIATE,
            prerequisites=("collision_predict",),
            group="Bumper Cars",
        ),
        m(
            "collision_bounce",
            "bumper_cars",
            "Bounced a light car backward off a heavy one",
            "Reflect a light car from a heavy one.",
            ("Make Car B much heavier.", "Use bouncy bumpers."),
            MissionType.COMPARISON,
            Difficulty.ADVANCED,
            ("collision_predict",),
            hidden=True,
            group="Bumper Cars",
        ),
        m(
            "incline_predict",
            "inclined_plane",
            "Predicted whether the block slides",
            "Predict motion before running the ramp.",
            ("Compare downhill gravity with maximum static friction.",),
            MissionType.EXPLANATION,
            group="Inclined Plane",
        ),
        m(
            "incline_slide",
            "inclined_plane",
            "Made the block slide",
            "Create a setup where gravity defeats friction.",
            ("Raise the angle or lower friction.",),
            prerequisites=("incline_predict",),
            group="Inclined Plane",
        ),
        m(
            "incline_threshold",
            "inclined_plane",
            "Found the slipping threshold",
            "Run within two degrees of the critical angle.",
            ("The threshold satisfies tan(angle) = static friction.",),
            MissionType.COMPARISON,
            Difficulty.INTERMEDIATE,
            ("incline_predict",),
            group="Inclined Plane",
        ),
        m(
            "lever_predict",
            "torque_levers",
            "Predicted which side turns",
            "Predict the lever direction before running it.",
            ("Compare force times distance from the pivot.",),
            MissionType.EXPLANATION,
            group="Torque and Levers",
        ),
        m(
            "lever_balance",
            "torque_levers",
            "Balanced the lever",
            "Make clockwise and counterclockwise torques match.",
            ("Set effort force × arm equal to load force × arm.",),
            prerequisites=("lever_predict",),
            group="Torque and Levers",
        ),
        m(
            "lever_advantage",
            "torque_levers",
            "Built a powerful lever",
            "Create mechanical advantage of at least three.",
            ("Use a long effort arm and short load arm.",),
            MissionType.COMPARISON,
            Difficulty.INTERMEDIATE,
            ("lever_predict",),
            group="Torque and Levers",
        ),
        m(
            "com_predict",
            "center_of_mass",
            "Predicted the balance point",
            "Predict which way the center of mass shifts.",
            ("It moves toward larger masses.",),
            MissionType.EXPLANATION,
            group="Center of Mass",
        ),
        m(
            "com_origin",
            "center_of_mass",
            "Balanced at the origin",
            "Put the center of mass within 0.1 m of zero.",
            ("Balance mass × position on both sides.",),
            prerequisites=("com_predict",),
            group="Center of Mass",
        ),
        m(
            "com_three",
            "center_of_mass",
            "Balanced three objects",
            "Complete a run with three positive masses.",
            ("Give the optional third object some mass.",),
            MissionType.COMPARISON,
            Difficulty.INTERMEDIATE,
            ("com_predict",),
            group="Center of Mass",
        ),
        m(
            "coaster_predict",
            "roller_coaster",
            "Predicted the energy exchange",
            "Predict how height changes speed.",
            ("Potential energy becomes kinetic energy downhill.",),
            MissionType.EXPLANATION,
            group="Roller-Coaster Energy",
        ),
        m(
            "coaster_complete",
            "roller_coaster",
            "Completed the whole track",
            "Build a track the coaster can physically finish.",
            ("Lower the middle hill or add starting speed.",),
            prerequisites=("coaster_predict",),
            group="Roller-Coaster Energy",
        ),
        m(
            "coaster_fast",
            "roller_coaster",
            "Built a 20 m/s coaster",
            "Reach a maximum speed of at least 20 m/s.",
            ("Start higher and finish lower.",),
            difficulty=Difficulty.INTERMEDIATE,
            prerequisites=("coaster_predict",),
            group="Roller-Coaster Energy",
        ),
        m(
            "coaster_loss_compare",
            "roller_coaster",
            "Finished despite energy losses",
            "Complete a track with dissipative loss enabled.",
            ("Leave enough initial energy for frictional losses.",),
            MissionType.COMPARISON,
            Difficulty.INTERMEDIATE,
            ("coaster_predict",),
            group="Roller-Coaster Energy",
        ),
        m(
            "rotation_predict",
            "rotational_motion",
            "Predicted which body spins faster",
            "Predict how moment of inertia affects acceleration.",
            ("For the same torque, smaller inertia means larger acceleration.",),
            MissionType.EXPLANATION,
            group="Rotational Motion",
        ),
        m(
            "rotation_spin",
            "rotational_motion",
            "Spun past 10 rad/s",
            "Reach at least 10 radians per second.",
            ("Increase torque or reduce inertia.",),
            prerequisites=("rotation_predict",),
            group="Rotational Motion",
        ),
        m(
            "rotation_energy",
            "rotational_motion",
            "Stored 100 joules of rotation",
            "Reach at least 100 J of rotational kinetic energy.",
            ("Energy grows with angular speed squared.",),
            difficulty=Difficulty.INTERMEDIATE,
            prerequisites=("rotation_predict",),
            group="Rotational Motion",
        ),
        m(
            "rotation_shape_compare",
            "rotational_motion",
            "Compared inertia shapes",
            "Run a supported body-shape inertia model.",
            ("Compare a hoop and solid disk with the same mass and radius.",),
            MissionType.COMPARISON,
            prerequisites=("rotation_predict",),
            group="Rotational Motion",
        ),
        m(
            "wave_predict",
            "wave_interference",
            "Predicted constructive interference",
            "Predict what in-phase waves do.",
            ("Add their displacements point by point.",),
            MissionType.EXPLANATION,
            group="Wave Interference",
        ),
        m(
            "wave_constructive",
            "wave_interference",
            "Made waves reinforce",
            "Create nearly complete constructive interference.",
            ("Match wavelength, frequency, and phase.",),
            prerequisites=("wave_predict",),
            group="Wave Interference",
        ),
        m(
            "wave_destructive",
            "wave_interference",
            "Made waves cancel",
            "Create strong destructive interference.",
            ("Use equal waves separated by 180°.",),
            difficulty=Difficulty.INTERMEDIATE,
            prerequisites=("wave_predict",),
            group="Wave Interference",
        ),
        m(
            "wave_phase_compare",
            "wave_interference",
            "Compared phase relationships",
            "Run the in-phase versus opposite-phase comparison.",
            ("Open Compare mode.",),
            MissionType.COMPARISON,
            prerequisites=("wave_predict",),
            group="Wave Interference",
        ),
        m(
            "doppler_predict",
            "doppler_effect",
            "Predicted the approaching pitch",
            "Predict the pitch of an approaching siren.",
            ("Compressed wavefronts arrive more often.",),
            MissionType.EXPLANATION,
            group="Sound and Doppler Effect",
        ),
        m(
            "doppler_high",
            "doppler_effect",
            "Raised the observed pitch by 20%",
            "Create an observed frequency at least 20% above the source.",
            ("Move the source toward the observer or observer toward the source.",),
            prerequisites=("doppler_predict",),
            group="Sound and Doppler Effect",
        ),
        m(
            "doppler_low",
            "doppler_effect",
            "Lowered the observed pitch by 20%",
            "Create an observed frequency at least 20% below the source.",
            ("Make the source and observer separate faster.",),
            difficulty=Difficulty.INTERMEDIATE,
            prerequisites=("doppler_predict",),
            group="Sound and Doppler Effect",
        ),
        m(
            "doppler_compare",
            "doppler_effect",
            "Compared approach and recession",
            "Run the approaching-versus-receding comparison.",
            ("Use Compare mode.",),
            MissionType.COMPARISON,
            prerequisites=("doppler_predict",),
            group="Sound and Doppler Effect",
        ),
        m(
            "optics_predict",
            "reflection_refraction",
            "Predicted the reflected angle",
            "Use the law of reflection before tracing rays.",
            ("Measure both angles from the normal.",),
            MissionType.EXPLANATION,
            group="Reflection and Refraction",
        ),
        m(
            "optics_reflect",
            "reflection_refraction",
            "Verified the law of reflection",
            "Run a ray and confirm equal incident and reflected angles.",
            ("Any valid incident angle works.",),
            prerequisites=("optics_predict",),
            group="Reflection and Refraction",
        ),
        m(
            "optics_tir",
            "reflection_refraction",
            "Created total internal reflection",
            "Send light from higher to lower index above the critical angle.",
            ("Try glass to air at a steep angle.",),
            difficulty=Difficulty.INTERMEDIATE,
            prerequisites=("optics_predict",),
            group="Reflection and Refraction",
        ),
        m(
            "optics_index_compare",
            "reflection_refraction",
            "Compared medium order",
            "Compare air-to-glass with glass-to-air.",
            ("Use Compare mode.",),
            MissionType.COMPARISON,
            prerequisites=("optics_predict",),
            group="Reflection and Refraction",
        ),
        m(
            "lens_predict",
            "thin_lenses",
            "Predicted a real lens image",
            "Predict the image from a converging lens beyond focus.",
            ("Principal rays meet on the far side.",),
            MissionType.EXPLANATION,
            group="Thin Lenses",
        ),
        m(
            "lens_real",
            "thin_lenses",
            "Formed a real image",
            "Place an object beyond a converging lens's focal point.",
            ("Use positive focal length and object distance greater than it.",),
            prerequisites=("lens_predict",),
            group="Thin Lenses",
        ),
        m(
            "lens_virtual",
            "thin_lenses",
            "Formed a virtual image",
            "Create an image with negative image distance.",
            ("Use a diverging lens or put the object inside a converging focus.",),
            prerequisites=("lens_predict",),
            group="Thin Lenses",
        ),
        m(
            "lens_compare",
            "thin_lenses",
            "Compared converging and diverging lenses",
            "Run both lens signs with the same object.",
            ("Use Compare mode.",),
            MissionType.COMPARISON,
            prerequisites=("lens_predict",),
            group="Thin Lenses",
        ),
        m(
            "field_predict",
            "electric_fields",
            "Predicted the positive-charge field",
            "Predict the field direction around a positive source.",
            ("Imagine releasing a tiny positive test charge.",),
            MissionType.EXPLANATION,
            group="Electric Fields",
        ),
        m(
            "field_dipole",
            "electric_fields",
            "Built an electric dipole",
            "Run with at least one positive and one negative source.",
            ("Give two charges opposite signs.",),
            prerequisites=("field_predict",),
            group="Electric Fields",
        ),
        m(
            "field_zero_force",
            "electric_fields",
            "Found a nearly force-free point",
            "Place the test charge where the net force is tiny.",
            ("Try symmetry between equal like charges, away from either singularity.",),
            difficulty=Difficulty.ADVANCED,
            prerequisites=("field_predict",),
            group="Electric Fields",
        ),
        m(
            "field_compare",
            "electric_fields",
            "Compared like and opposite charges",
            "Run the like-charge versus dipole comparison.",
            ("Use Compare mode.",),
            MissionType.COMPARISON,
            prerequisites=("field_predict",),
            group="Electric Fields",
        ),
        m(
            "magnetic_predict",
            "magnetic_forces",
            "Predicted the parallel-field force",
            "Predict force when motion and field are parallel.",
            ("The cross product contains sin θ.",),
            MissionType.EXPLANATION,
            group="Magnetic Forces",
        ),
        m(
            "magnetic_zero",
            "magnetic_forces",
            "Made the magnetic force vanish",
            "Align motion or current parallel to the field.",
            ("Use 0° or 180° between vectors.",),
            prerequisites=("magnetic_predict",),
            group="Magnetic Forces",
        ),
        m(
            "magnetic_reverse",
            "magnetic_forces",
            "Sent force into the screen",
            "Create a negative signed z-force.",
            ("Reverse charge, current, or vector order.",),
            difficulty=Difficulty.INTERMEDIATE,
            prerequisites=("magnetic_predict",),
            group="Magnetic Forces",
        ),
        m(
            "magnetic_wire",
            "magnetic_forces",
            "Pushed a current-carrying wire",
            "Run the wire-force experiment.",
            ("Choose Current-carrying wire.",),
            prerequisites=("magnetic_predict",),
            group="Magnetic Forces",
        ),
        m(
            "magnetic_compare",
            "magnetic_forces",
            "Compared perpendicular and parallel vectors",
            "Run the angle comparison.",
            ("Use Compare mode.",),
            MissionType.COMPARISON,
            prerequisites=("magnetic_predict",),
            group="Magnetic Forces",
        ),
        m(
            "buoy_predict",
            "buoyancy",
            "Predicted whether a light object floats",
            "Predict the state from density comparison.",
            ("Compare object density with fluid density.",),
            MissionType.EXPLANATION,
            group="Buoyancy",
        ),
        m(
            "buoy_float",
            "buoyancy",
            "Made an object float",
            "Run an object less dense than its fluid.",
            ("Lower object density or increase fluid density.",),
            prerequisites=("buoy_predict",),
            group="Buoyancy",
        ),
        m(
            "buoy_neutral",
            "buoyancy",
            "Achieved neutral buoyancy",
            "Match effective object and fluid density.",
            ("Use exactly equal densities.",),
            difficulty=Difficulty.INTERMEDIATE,
            prerequisites=("buoy_predict",),
            group="Buoyancy",
        ),
        m(
            "buoy_compare",
            "buoyancy",
            "Compared two fluids",
            "Run water versus denser-fluid comparison.",
            ("Use Compare mode.",),
            MissionType.COMPARISON,
            prerequisites=("buoy_predict",),
            group="Buoyancy",
        ),
        m(
            "pressure_predict",
            "fluid_pressure",
            "Predicted the depth effect",
            "Predict how pressure changes with depth.",
            ("Think about the weight of fluid overhead.",),
            MissionType.EXPLANATION,
            group="Fluid Pressure",
        ),
        m(
            "pressure_deep",
            "fluid_pressure",
            "Measured near the bottom",
            "Measure at least 80% of the container depth.",
            ("Move the depth control close to maximum.",),
            prerequisites=("pressure_predict",),
            group="Fluid Pressure",
        ),
        m(
            "pressure_double",
            "fluid_pressure",
            "Created two atmospheres of gauge pressure",
            "Reach gauge pressure of at least 202.65 kPa.",
            ("Use a dense fluid, strong gravity, or greater depth.",),
            difficulty=Difficulty.ADVANCED,
            prerequisites=("pressure_predict",),
            group="Fluid Pressure",
        ),
        m(
            "pressure_compare",
            "fluid_pressure",
            "Compared shallow and deep pressure",
            "Run the depth comparison.",
            ("Use Compare mode.",),
            MissionType.COMPARISON,
            prerequisites=("pressure_predict",),
            group="Fluid Pressure",
        ),
        m(
            "gas_predict",
            "gas_laws",
            "Predicted Boyle's compression",
            "Predict pressure when isothermal volume is halved.",
            ("PV stays constant.",),
            MissionType.EXPLANATION,
            group="Gas Laws",
        ),
        m(
            "gas_boyle",
            "gas_laws",
            "Ran Boyle's law",
            "Complete an isothermal pressure–volume process.",
            ("Choose Boyle's law.",),
            prerequisites=("gas_predict",),
            group="Gas Laws",
        ),
        m(
            "gas_charles",
            "gas_laws",
            "Ran Charles's law",
            "Complete a constant-pressure volume–temperature process.",
            ("Choose Charles's law.",),
            prerequisites=("gas_predict",),
            group="Gas Laws",
        ),
        m(
            "gas_gay_lussac",
            "gas_laws",
            "Ran Gay-Lussac's law",
            "Complete a constant-volume pressure–temperature process.",
            ("Choose Gay-Lussac's law.",),
            prerequisites=("gas_predict",),
            group="Gas Laws",
        ),
        m(
            "gas_compare",
            "gas_laws",
            "Compared constrained gas processes",
            "Compare compression with heating.",
            ("Use Compare mode.",),
            MissionType.COMPARISON,
            prerequisites=("gas_predict",),
            group="Gas Laws",
        ),
        m(
            "diffusion_predict",
            "diffusion",
            "Predicted diffusive spreading",
            "Predict how mean-squared displacement changes with time.",
            ("Squared distances do not cancel.",),
            MissionType.EXPLANATION,
            group="Diffusion and Random Walks",
        ),
        m(
            "diffusion_unbiased",
            "diffusion",
            "Released unbiased walkers",
            "Run a walk with zero directional bias.",
            ("Set both bias controls to zero.",),
            prerequisites=("diffusion_predict",),
            group="Diffusion and Random Walks",
        ),
        m(
            "diffusion_two_d",
            "diffusion",
            "Explored two dimensions",
            "Run particles that can move horizontally and vertically.",
            ("Choose 2D.",),
            prerequisites=("diffusion_predict",),
            group="Diffusion and Random Walks",
        ),
        m(
            "diffusion_bias",
            "diffusion",
            "Created directed drift",
            "Run with a noticeable directional bias.",
            ("Move a bias control beyond 0.10.",),
            prerequisites=("diffusion_predict",),
            group="Diffusion and Random Walks",
        ),
        m(
            "diffusion_compare",
            "diffusion",
            "Compared drift and diffusion",
            "Run the unbiased-versus-biased comparison.",
            ("Use Compare mode.",),
            MissionType.COMPARISON,
            prerequisites=("diffusion_predict",),
            group="Diffusion and Random Walks",
        ),
    )
}
MISSIONS_BY_SIMULATION = {
    sim: tuple(item for item in MISSION_DEFINITIONS.values() if item.simulation_id == sim)
    for sim in {item.simulation_id for item in MISSION_DEFINITIONS.values()}
}
